server:
  port: 9000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ccu_v3_b
    username: root
    password: admin
logging:
  path: application.log

      
      
       